const average = (data) => {
  return data.reduce((acc, val) => acc + val, 0) / data.length
}

export const variance = (data) => {
  const averageNum = average(data)
  return data.map(item => ((item - averageNum) ** 2)).reduce((acc, val) => acc + val, 0) / data.length
}

self.addEventListener('message', ({ data: { data }}) => {
  let out
  // 模拟大量运算
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  out = variance(data)
  self.postMessage({ data: out })
})
